networks:
  trip-manager-network:

services:
  postgres:
    image: postgres:18-alpine
    container_name: trip-manager-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/dbdata:/var/lib/postgresql/data
    networks:
      - trip-manager-network

  trip-manager:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 22
    container_name: trip-manager
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - trip-manager-network

volumes:
  postgres-data:
